### ISSUE TITLE
`REBUILD_DOCKER=true ./runtest.sh` fails locally

### ISSUE THREAD

**Issue by acmiyaguchi** [mozilla/python_moztelemetry#219]
```
Successfully tagged moztelemetry_docker:python-2.7
running pytest
Traceback (most recent call last):
  File "setup.py", line 27, in <module>
    tests_require=['python_moztelemetry[test]'],
  File "/miniconda/envs/test-environment/lib/python2.7/distutils/core.py", line 151, in setup
    dist.run_commands()
  File "/miniconda/envs/test-environment/lib/python2.7/distutils/dist.py", line 953, in run_commands
    self.run_command(cmd)
  File "/miniconda/envs/test-environment/lib/python2.7/distutils/dist.py", line 972, in run_command
    cmd_obj.run()
  File "/python_moztelemetry/.eggs/pytest_runner-2.9-py2.7.egg/ptr.py", line 73, in run
  File "/miniconda/envs/test-environment/lib/python2.7/site-packages/setuptools/dist.py", line 456, in fetch_build_eggs
    replace_conflicting=True,
  File "/miniconda/envs/test-environment/lib/python2.7/site-packages/pkg_resources/__init__.py", line 875, in resolve
    new_requirements = dist.requires(req.extras)[::-1]
  File "/miniconda/envs/test-environment/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2615, in requires
    "%s has no such extra feature %r" % (self, ext)
pkg_resources.UnknownExtra: python-moztelemetry 0.9.2.dev13+ng7a35638.d20180802 has no such extra feature 'test'
Coverage.py warning: No data was collected. (no-data-collected)
```

**Comment by acmiyaguchi** [comment]
I cleared my cache and reran against master, I can't seem to reproduce this.
